# **머신러닝(Machine Learning) 기초**
* https://scikit-learn.org/stable/

> 지도 학습(Supervised Learning)<br>
     : 정답(라벨)이 포함된 데이터를 바탕으로 모델을 훈련시켜 예측이나 분류를 수행하는 방식<br>
> 비지도 학습(Unsupervised Learning)<br>
     : 정답이 없는 데이터에서 컴퓨터가 스스로 공통된 특징이나 규칙, 클러스터(군집)를 찾아내는 방식<br>

> 분류(Classification) <br>
> 회귀(Regression) <br>
> 군집(Clustering) <br>

# **[1] Data Load**
* https://scikit-learn.org/1.1/modules/generated/sklearn.datasets.load_boston.html

In [1]:
from sklearn import set_config
set_config(display="text")

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../datas/BostonHousing.csv")
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
df.columns = df.columns.str.upper()

In [5]:
df.head(3)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7

# **[2] 문제지 답안지 분리**

```python
sklearn.model_selection.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)


wooriinjae.ai.vision.add(num1, num2)

## 문제지(X)

In [6]:
X = df.drop(columns=["MEDV"])
X.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.9,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14

## 답안지(y)

In [7]:
y = df['MEDV']
y.head(2)

0    24.0
1    21.6
Name: MEDV, dtype: float64

## 문제지,답안지 분리(train_test_split)

In [8]:
from sklearn.model_selection import train_test_split

X_train7, X_test3,    y_train7, y_test3 = train_test_split( X, y, test_size=0.3, random_state=1234)

In [9]:
X_train7.shape, X_test3.shape,    y_train7.shape, y_test3.shape

((354, 13), (152, 13), (354,), (152,))

# **모델선택**

``` python
class sklearn.linear_model.LinearRegression(*, fit_intercept=True, copy_X=True, tol=1e-06, n_jobs=None, positive=False)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()  #생성자함수,메모리초기화

# **학습(fit)**

In [19]:
#lr.fit?

In [12]:
lr.fit(X_train7, y_train7)

LinearRegression()

# **예측(predict)**

In [21]:
#lr.predict?

In [24]:
pred = lr.predict(X_test3)
pred[:10]

array([21.16871632, 24.00813263, 11.98549629, 21.6631808 , 14.18880555,
       27.52381606, 21.37823548, 19.38327949, 27.05874719, 34.35881273])

# **평가**
* https://scikit-learn.org/stable/modules/model_evaluation.html#mean-squared-error

In [25]:
y_test3[:10]

64     33.0
100    27.5
400     5.6
485    21.2
454    14.9
288    22.3
112    18.8
478    14.6
66     19.4
187    32.0
Name: MEDV, dtype: float64

In [22]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test3, pred)
print( np.sqrt(mse) )

4.910525893692263